# Site settings
title: "The Comparative Toxicology Lab"
logo: "assets/images/example-logo.png"
masthead_title: ""
masthead_nav: true

description: >-
  Comparative toxicology across species to understand chemical sensitivity,
  develop new approach methodologies, and improve environmental and human health
  risk assessment.

twitter_username:
github_username:
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes"

permalink: /:categories/:title/

timezone:

include:
  - _pages

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Author sidebar defaults (we will override this later)
author:
  name   : " "
  avatar : "/assets/images/bio-photo.jpg"
  bio    : " "
  links: []

# Footer (optional)
footer:
  links: []

# -------------------------
# MAIN NAVIGATION MENU
# -------------------------
main:
  - title: "Research"
    url: /research/
  - title: "People"
    url: /people/
  - title: "Publications"
    url: /publications/
  - title: "News"
    url: /news/
  - title: "Positions"
    url: /positions/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: false
      share: false
      related: false

  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false

# Archives
category_archive:
  type: liquid
  path: /categories/

tag_archive:
  type: liquid
  path: /tags/
